# Generated by Django 6.0.4 on 2026-04-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="chunk_size",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
