# Generated by Django 6.0.4 on 2026-04-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0002_usersession_chunk_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="text",
            name="language",
            field=models.CharField(default="English", max_length=20),
        ),
    ]
