# Generated by Django 6.0.4 on 2026-04-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0003_text_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="reading_mode",
            field=models.CharField(default="highlight", max_length=20),
        ),
    ]
