# Generated by Django 6.0.4 on 2026-04-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0005_badge_userbadge"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="current_streak",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_session_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="longest_streak",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
