# Generated by Django 6.0.4 on 2026-04-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0008_lesson_speedreadingqa_assistantmessage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="font_family",
            field=models.CharField(default="Lora", max_length=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="font_size",
            field=models.CharField(default="1.2rem", max_length=10),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="line_spacing",
            field=models.CharField(default="2.0", max_length=10),
        ),
    ]
