# """
# Django settings for speedreading project.

# Generated by 'django-admin startproject' using Django 6.0.4.

# For more information on this file, see
# https://docs.djangoproject.com/en/6.0/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/6.0/ref/settings/
# """
# from dotenv import load_dotenv
# load_dotenv()
# from pathlib import Path
# import os
# ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY")
# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = "django-insecure-_o*k3&y7++2q&-i)fzb_s71lhykv$&dscky_-ykdokq!h#ds&2"

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []


# # Application definition

# INSTALLED_APPS = [
#     'jazzmin',    
#     "django.contrib.admin",
#     "django.contrib.auth",
#     "django.contrib.contenttypes",
#     "django.contrib.sessions",
#     "django.contrib.messages",
#     "django.contrib.staticfiles",
#      'crispy_forms',
#     'crispy_bootstrap5',
#     'reader',
# ]

# MIDDLEWARE = [
#     "django.middleware.security.SecurityMiddleware",
#     "django.contrib.sessions.middleware.SessionMiddleware",
#     "django.middleware.common.CommonMiddleware",
#     "django.middleware.csrf.CsrfViewMiddleware",
#     "django.contrib.auth.middleware.AuthenticationMiddleware",
#     "django.contrib.messages.middleware.MessageMiddleware",
#     "django.middleware.clickjacking.XFrameOptionsMiddleware",
# ]

# ROOT_URLCONF = "speedreading.urls"

# TEMPLATES = [
#     {
#         "BACKEND": "django.template.backends.django.DjangoTemplates",
#         "DIRS": [],
#         "APP_DIRS": True,
#         "OPTIONS": {
#             "context_processors": [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = "speedreading.wsgi.application"


# # Database
# # https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }


# # Password validation
# # https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/6.0/topics/i18n/

# LANGUAGE_CODE = "en-us"

# TIME_ZONE = "UTC"

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/6.0/howto/static-files/

# STATIC_URL = "static/"

# JAZZMIN_SETTINGS = {
#     "site_title": "Speed Reader Admin",
#     "site_header": "Speed Reader",
#     "site_brand": "⚡ Speed Reader",
#     "welcome_sign": "Welcome to Speed Reader Admin Panel",
#     "copyright": "Sirius Academy",

#     "show_sidebar": True,
#     "navigation_expanded": True,

#     "icons": {
#         "auth":                  "fas fa-users-cog",
#         "auth.user":             "fas fa-user",
#         "reader.subject":        "fas fa-book",
#         "reader.text":           "fas fa-file-alt",
#         "reader.quiz":           "fas fa-question-circle",
#         "reader.userprofile":    "fas fa-chart-line",
#         "reader.usersession":    "fas fa-stopwatch",
#     },

#     "order_with_respect_to": [
#         "reader.subject",
#         "reader.text",
#         "reader.quiz",
#         "reader.userprofile",
#         "reader.usersession",
#     ],

#     "topmenu_links": [
#         {"name": "Home", "url": "admin:index"},
#         {"name": "View Site", "url": "/"},
#     ],
# }

# JAZZMIN_UI_TWEAKS = {
#     "theme": "darkly",          # dark beautiful theme
#     "dark_mode_theme": "darkly",
#     "navbar_small_text": False,
#     "footer_small_text": False,
#     "body_small_text": False,
#     "brand_small_text": False,
#     "brand_colour": "navbar-dark",
#     "accent": "accent-primary",
#     "navbar": "navbar-dark",
#     "sidebar": "sidebar-dark-primary",
#     "button_classes": {
#         "primary":  "btn-primary",
#         "secondary":"btn-secondary",
#         "info":     "btn-info",
#         "warning":  "btn-warning",
#         "danger":   "btn-danger",
#         "success":  "btn-success",
#     }
# }
# CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
# CRISPY_TEMPLATE_PACK = "bootstrap5"

# LOGIN_URL = '/login/'
# LOGIN_REDIRECT_URL = '/dashboard/'
# LOGOUT_REDIRECT_URL = '/login/'

from pathlib import Path
from dotenv import load_dotenv
from decouple import config
import dj_database_url
import os

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

# ── SECURITY ──────────────────────────────────────────
SECRET_KEY = config('SECRET_KEY', default='your-local-dev-key-change-in-production')
DEBUG      = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.railway.app',
]

CSRF_TRUSTED_ORIGINS = [
    'https://*.railway.app',
]

# ── APPS ──────────────────────────────────────────────
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap5',
    'reader',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK          = "bootstrap5"

# ── MIDDLEWARE ────────────────────────────────────────
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # ← must be second!
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'speedreading.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':    [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'speedreading.wsgi.application'

# ── DATABASE ──────────────────────────────────────────
DATABASE_URL = config('DATABASE_URL', default=None)

if DATABASE_URL:
    # Railway PostgreSQL
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Local SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME':   BASE_DIR / 'db.sqlite3',
        }
    }

# ── AUTH ──────────────────────────────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LOGIN_URL          = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL= '/login/'

# ── INTERNATIONALISATION ──────────────────────────────
LANGUAGE_CODE = 'en-us'
TIME_ZONE     = 'Asia/Jerusalem'
USE_I18N      = True
USE_TZ        = True

# ── STATIC FILES ──────────────────────────────────────
STATIC_URL  = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
STATICFILES_DIRS = [
    BASE_DIR / 'speedreading' / 'static',
]

# ── MEDIA ─────────────────────────────────────────────
MEDIA_URL  = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ── DEFAULT PK ────────────────────────────────────────
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── ANTHROPIC ─────────────────────────────────────────
ANTHROPIC_API_KEY = config('ANTHROPIC_API_KEY', default='')

# ── JAZZMIN ───────────────────────────────────────────
JAZZMIN_SETTINGS = {
    "site_title":   "Speed Reader Admin",
    "site_header":  "Speed Reader",
    "site_brand":   "⚡ Speed Reader",
    "welcome_sign": "Welcome to Speed Reader Admin Panel",
    "copyright":    "Sirius Academy",
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "auth":               "fas fa-users-cog",
        "auth.user":          "fas fa-user",
        "reader.subject":     "fas fa-book",
        "reader.text":        "fas fa-file-alt",
        "reader.quiz":        "fas fa-question-circle",
        "reader.userprofile": "fas fa-chart-line",
        "reader.usersession": "fas fa-stopwatch",
    },
    # ── TOP MENU ──────────────────────────────────
    "topmenu_links": [
        {
            "name": "🏠 Back to SpeedReader",
            "url":  "/dashboard/",
            "new_window": False,
        },
        {
            "name": "📚 Subjects",
            "url":  "/subjects/",
            "new_window": False,
        },
        {
            "name": "📅 Daily Challenge",
            "url":  "/daily/",
            "new_window": False,
        },
    ],
}

JAZZMIN_UI_TWEAKS = {
    "theme":              "darkly",
    "default_theme_mode": "dark",   # ← new correct setting
    "navbar":             "navbar-dark",
    "sidebar":            "sidebar-dark-primary",
}

WHITENOISE_USE_FINDERS       = True
WHITENOISE_AUTOREFRESH       = True
WHITENOISE_SKIP_COMPRESS_EXTENSIONS = []